import {mkdir,writeFile,cp,readFile} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {escapeHtml as esc,code} from '../site/assets/model.mjs';
import {bitmapSvg,parseHex} from '../site/assets/unifont-model.mjs';

export function coordinateProof(glyph){
  return `<div class="coordinate-proof"><div class="pixel-x-axis">${Array.from({length:glyph.width},(_,i)=>`<span>${i}</span>`).join('')}</div><div class="pixel-y-axis">${Array.from({length:16},(_,i)=>`<span>${i}</span>`).join('')}</div>${bitmapSvg(glyph,8,true)}</div>`;
}
export function proofCard(glyph,donorMap){
  const donors=glyph.donors.map(value=>{const point=parseInt(value,16),donor=donorMap.get(point);return `<figure><figcaption>U+${value} ${String.fromCodePoint(point)}</figcaption>${bitmapSvg(donor,4)}</figure>`;}).join('');
  const sequence=[donorMap.get(0x6e),glyph,donorMap.get(0x6f),glyph,donorMap.get(0x131),glyph,donorMap.get(0x6d),glyph];
  return `<article class="foundation-card" id="bitmap-${glyph.codePoint.toString(16)}" data-proof-glyph="${esc(glyph.glyphId)}"><header><p class="code">${code(glyph.codePoint)} · ${glyph.width} × 16</p><h2>${esc(glyph.canonicalName)}</h2></header><div class="foundation-drawings"><figure><figcaption>8× · pixel coordinates</figcaption>${coordinateProof(glyph)}</figure><figure><figcaption>8× · clear</figcaption>${bitmapSvg(glyph,8)}</figure><figure><figcaption>Quintessential Serif</figcaption><span class="outline-reference" aria-label="${esc(glyph.name)}">${String.fromCodePoint(glyph.codePoint)}</span></figure></div><div class="foundation-small"><figure><figcaption>1×</figcaption>${bitmapSvg(glyph)}</figure><figure><figcaption>2×</figcaption>${bitmapSvg(glyph,2)}</figure><figure><figcaption>Repeated at 1×</figcaption><span class="bitmap-sequence">${Array.from({length:6},()=>bitmapSvg(glyph)).join('')}</span></figure><figure><figcaption>Mixed with native Latin</figcaption><span class="bitmap-sequence">${sequence.map(item=>bitmapSvg(item)).join('')}</span></figure></div><div class="foundation-donors">${donors}</div><p class="drawing-note">${esc(glyph.notes)}</p>${glyph.reviewNotes?.length?`<ul class="drawing-review-notes">${glyph.reviewNotes.map(note=>`<li>${esc(note)}</li>`).join('')}</ul>`:''}<details class="proof-details"><summary>HEX &amp; structural checks</summary><code>${glyph.line}</code><p>${glyph.assessment.components} connected body · ${glyph.assessment.counters} enclosed ${glyph.assessment.counters===1?'space':'spaces'}</p><p>${glyph.assessment.flags.length} pixel flags: ${[...new Set(glyph.assessment.flags.map(flag=>flag.kind))].join(', ')||'none'}.</p>${glyph.assessment.flags.length?`<ul>${glyph.assessment.flags.map(flag=>`<li>${esc(flag.kind)}${flag.axis?` (${flag.axis})`:""}: ${flag.pixels.map(([x,y])=>`(${x},${y})`).join(" ")}</li>`).join("")}</ul>`:""}<p class="code">Bitmap SHA-256 ${glyph.bitmapSha256}</p><p class="code">Proof-input SHA-256 ${glyph.proofSha256}</p></details></article>`;
}
const documentShell=(heading,body,metadata)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(heading)} · Unifont proofs</title><link rel="stylesheet" href="../../assets/style.css"><link rel="stylesheet" href="../../assets/unifont.css"></head><body class="unifont-proof-page"><header class="proof-page-header"><a href="../../unifont.html">← Unifont charts</a><a href="foundation.html">Review index</a><a href="donors.html">Native donors</a></header><main class="proof-main"><h1>${esc(heading)}</h1><p class="lead">Bitmap drawings for review · 8 × 16 pixels · ${metadata.drawn} drawn / ${metadata.total} characters</p><p class="proof-status">Complete repertoire: 136 forms without middle components, 156 pairs and 192 quartets. Final aesthetic acceptance remains separate from agent inspection.</p>${body}<footer class="proof-provenance"><p>GNU Unifont ${metadata.upstreamVersion}. <a href="../OFL.txt">OFL 1.1 and attribution</a>. Reference font snapshot: <code>${metadata.reference.sha256}</code>.</p><p>The outline samples use the frozen Roman font copied with this proof. The bitmap enlargements show the exact HEX pixels.</p></footer></main></body></html>`;

export async function writeUnifontProofs(root,destination,metadata,donorSource,catalogue){
  const source=path.join(root,'resources/unifont');
  await mkdir(path.join(destination,'unifont/proofs'),{recursive:true});
  await cp(source,path.join(destination,'unifont'),{recursive:true});
  const reference=await readFile(path.join(root,metadata.reference.path));
  if(createHash('sha256').update(reference).digest('hex')!==metadata.reference.sha256)throw new Error('Reference font changed during Unifont proof build');
  await writeFile(path.join(destination,'unifont/reference.woff2'),reference);
  const donorMap=parseHex(donorSource),outputs={};
  const make=(name,title,body)=>{outputs[name]=documentShell(title,body,metadata);};
  const families=catalogue.families.filter(family=>metadata.glyphs.some(glyph=>glyph.familyId===family.id));
  const groupIds=new Set(metadata.groups.flatMap(group=>group.glyphIds));
  const primitive=metadata.glyphs.filter(glyph=>glyph.parts.length===1);
  const paired=metadata.glyphs.filter(glyph=>glyph.parts.length>1&&!groupIds.has(glyph.glyphId)&&metadata.foundationIds.includes(glyph.glyphId));
  const renderCards=glyphs=>`<div class="foundation-cards">${glyphs.map(glyph=>proofCard(glyph,donorMap)).join('')}</div>`;
  const links=`<nav class="proof-index"><a href="primitives.html">1 · All 16 primitives</a><a href="pairs.html">2 · Paired constructions</a><a href="stress.html">3 · Four-state stress groups</a><a href="expansions.html">4 · Forms without middle components</a><a href="donors.html">Native Unifont donors</a></nav>`;
  make('foundation.html','Unifont drawing review',`${links}<p>The native Latin terminal corrections are applied throughout this batch. All ${metadata.total.toLocaleString('en-US')} characters are drawn. Family proofs keep every short/extended pair and four-state group adjacent, including the original foundation stress groups.</p><h2>Changes from the foundation</h2><ul><li>Both turned open primitives and the stemless spine now exactly preserve the native Unifont terminals.</li><li><a href="pairs.html#bitmap-f2ad6">One-sided spines</a> exactly use native Unifont a and turned a. Shared spines combine their upper and lower connections in a balanced body with a thin waist.</li><li><a href="pairs.html#bitmap-f2aca">Turned double bowl</a> uses the native d/q lower return to remove the thick corner while retaining both counters.</li><li><a href="stress.html#dense-shared-spine">Narrow shared spines</a> place their crossover at row 9, one pixel higher.</li></ul><h2>By construction family</h2><ul class="proof-family-list">${families.map(family=>`<li><a href="${family.id}.html">${esc(family.title)}</a></li>`).join('')}</ul><h2>Review status</h2><p>${metadata.inspected} of ${metadata.drawn} drawings have a current recorded agent inspection. The user's foundation feedback authorized this expansion; final aesthetic acceptance remains separate.</p><p><a href="../glyphs.json">Drawing metadata and pixel flags</a> · <a href="../review.json">Inspection records</a> · <a href="../README.md">Editable sources and conventions</a></p>`);
  make('primitives.html','1 · Standalone primitives',links+renderCards(primitive));
  make('pairs.html','2 · Paired constructions',links+renderCards(paired));
  const renderGroup=group=>`<section class="stress-proof ${group.glyphIds.length===2?'pair-proof':'quartet-proof'}" id="${esc(group.id)}"><h2>${esc(group.title||metadata.glyphs.find(g=>g.glyphId===group.glyphIds[0]).canonicalName)}</h2><p class="prose">${esc(group.notes||'Compare the ordered middle components: unchanged body, independent extensions.')}</p>${renderCards(group.glyphIds.map(id=>metadata.glyphs.find(glyph=>glyph.glyphId===id)))}<details><summary>Exact changes from the unextended body</summary><ul>${group.differences.map(diff=>`<li>${esc(metadata.glyphs.find(glyph=>glyph.glyphId===diff.glyphId).canonicalName)}: ${diff.pixels.map(([x,y])=>`(${x},${y})`).join(' ')||'unchanged base'}</li>`).join('')}</ul></details></section>`;
  make('stress.html','3 · Four-state stress groups',links+metadata.groups.filter(group=>['four-stave-arches','adjacent-long-bowl-closure','dense-shared-spine'].includes(group.id)).map(renderGroup).join(''));
  make('expansions.html','4 · Complete group without middle components',links+families.filter(family=>metadata.glyphs.some(glyph=>glyph.familyId===family.id&&!glyph.parts.some(part=>part.middle))).map(family=>`<section class="extension-family"><h2>${esc(family.title)}</h2>${renderCards(metadata.glyphs.filter(glyph=>glyph.familyId===family.id&&!glyph.parts.some(part=>part.middle)))}</section>`).join(''));
  make('donors.html','Native Unifont donor pixels',`${links}<p>The exact pinned source pixels, before project adaptations. Each reference uses Unifont ${metadata.upstreamVersion}.</p><div class="donor-cards">${[...donorMap].map(([point,glyph])=>`<article><h2>U+${point.toString(16).toUpperCase().padStart(4,'0')} · ${String.fromCodePoint(point)}</h2>${coordinateProof(glyph)}<span class="bitmap-sequence">${bitmapSvg(glyph)}${bitmapSvg(glyph,2)}</span><code>${glyph.line}</code></article>`).join('')}</div>`);
  for(const family of families){
    const glyphs=metadata.glyphs.filter(glyph=>glyph.familyId===family.id);
    const groups=metadata.groups.filter(group=>glyphs.some(glyph=>glyph.glyphId===group.glyphIds[0]));
    make(family.id+'.html',family.title,links+(groups.length?groups.map(renderGroup).join(''):renderCards(glyphs)));
  }
  const hashes={};
  for(const [file,html] of Object.entries(outputs)){
    await writeFile(path.join(destination,'unifont/proofs',file),html);
    hashes[file]=createHash('sha256').update(html).digest('hex');
  }
  await writeFile(path.join(destination,'unifont/proofs/manifest.json'),JSON.stringify({schemaVersion:1,reference:metadata.reference,files:hashes},null,2)+'\n');
}
